Remove parameterless methods
akka/alpakka-kafka pull request #1288
Opened 2020-12-14 19:56 UTC by seglo

I noticed when upgrading from 2.0.5 to 2.1.0-M1 that if you reference `consumerDefaults` or `producerDefaults` with parens you will get a compile time error because they were dropped.  Should we keep the params for parameterless methods for 2.1.0?

2020-12-15 07:02 UTC, ennru approved these changes
LGTM.

2020-12-15 07:05 UTC, ennru requested changes
Hm, these are effectively `val`s, so they should stay without parens.

2020-12-15 16:27 UTC, seglo commented
That's true. My point is it will cause breaking changes for users who reference them as methods (with params). I'm on the fence if we should change it or not. It could be an annoyance for many who rely on the testkit.

2020-12-21 14:47 UTC, ennru commented
This problem shows with Scala 2.13.4 which is stricter about nullary methods and parens, right?

If we add the parens, they need to be added in the specs and examples that extend `KafkaTestKit` as well.

2020-12-21 14:51 UTC, ennru commented
Tried it on Alpakka Kafka with Scala 2.13.4 now, out own use of these values makes me believe we should not add parens.

`100 warnings found`...

2020-12-21 14:57 UTC, ennru commented
The parens appeared on `consumerSettings` in #1099 as part of 2.0.3 
https://github.com/akka/alpakka-kafka/pull/1099/files#diff-58a836c24b91550202dfa15b5a0aa7b66e4a16a503fb7e50039d1d6876d6d80eR43

So it was an oversight to add them there.

2020-12-21 16:06 UTC, seglo commented
Got it.  Closing this.

2020-12-21 16:06 UTC, closed without merging